### PR TITLE
free memory allocated by Golang using C.CString()

### LINKED ISSUE #391: The memory allocated by golang lib c-polygonid should be freed.
reference: https://github.com/0xPolygonID/c-polygonid/issues/72

Pull request here: https://github.com/0xPolygonID/polygonid-flutter-sdk/pull/390

1. iOS & Android libs are built based on this Pull Request in c-polygonid repo: https://github.com/0xPolygonID/c-polygonid/pull/73
2. Add PLGNFreeCString() call in flutter/dart code

### PR DESCRIPTION
**Pull request by yushihang**
close #391

### CODE REVIEW

**Comment by plusema86** [comment]
@olomix can you take a look a this PR?

**Comment by 5eeman** [comment]
I'm actually not sure why we're not making something like:
```
malloc.free(response.value);
```

Maybe this way we could also get rid of `PLGNFreeStatus`?

Or I don't know some background of this

**Comment by plusema86** [comment]
@yushihang we have already merged the [PR 386](https://github.com/0xPolygonID/polygonid-flutter-sdk/pull/386) with malloc.free() , is it enough?

**Comment by yushihang** [comment]
> @olomix can you take a look a this PR?



> I'm actually not sure why we're not making something like:
> 
> ```
> malloc.free(response.value);
> ```
> 
> Maybe this way we could also get rid of `PLGNFreeStatus`?
> 
> Or I don't know some background of this



> @yushihang we have already merged the [PR 386](https://github.com/0xPolygonID/polygonid-flutter-sdk/pull/386) with malloc.free() , is it enough?

@olomix @5eeman @plusema86 

Thank you very much for your response and suggestions.

A concise description is: "Follow the RAII ([Resource Acquisition Is Initialization](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization)) principle, who allocates, who releases."

I will try to express my understanding of this memory management case using the diagram A below:

flutter-release-memory-A


The steps in the diagram are as follows:

1.  Flutter/Dart allocates a block of memory with the size of a pointer to receive return data from Golang

    ```dart
    ffi.Pointer<ffi.Pointer<ffi.Char>> response =
         malloc<ffi.Pointer<ffi.Char>>();
    ```

    In other program languages, this variable is possibly allocated on the stack or in a register. There is an issue discussing why Flutter needs to allocate it on the heap using malloc: <https://github.com/dart-lang/sdk/issues/42509>

2.  Flutter call function provided by Golang, pass the pointer address(`response`) to Golang:

    ```go
    int res = PolygonIdCore.nativePolygonIdCoreLib
        .PLGNCreateClaim(response, in1, status);
    ```

3.  Golang allocate memory for returning data, write data(`string(respB)`) into the memory, and point `jsonResponse` to the memory.
    (This memory will not be managed by Golang's memory garbage collector)

    ```go
    *jsonResponse = C.CString(string(respB))
    ```

4.  Flutter side return data from Golang allocated memory (`jsonResponse`)

    ```dart
    ffi.Pointer<ffi.Char> jsonResponse = response.value;
    ```

5.  After `jsonResponse` is no longer needed, it should be released.
    So we call another function from Flutter/dart to notify Golang to release the memory allocated for `jsonResponse` in step 3.

    ```dart
    PolygonIdCore.nativePolygonIdCoreLib.PLGNFreeCString(jsonResponse);
    ```

6.  Golang release memory for `jsonResponse`

    ```go
    C.free(unsafe.Pointer(str))
    ```

7.  Flutter /Dart release to memory allocated for the pointer （`response`） (allcated in step 1)
    ```dart
    malloc.free(response);
    ```

After following this procedure, all memory on the heap that was dynamically allocated (the green and red parts in Diagram A) will be properly released, and there will be no memory leak.

PR #386 handles the release logic for the red memory in Diagram A, while the current PR handles the release logic for the green memory.

Another point that needs to be discussed for current PR is "why we need to wrap a function in Go to release `jsonResponse`, instead of calling the c free function directly in flutter/dart". Is that right?

I have attempted to illustrate this implementation method using Diagram B:

flutter-release-memory-B


As can be seen from the diagram, steps 5 and 6 in Diagram A have been combined into a new step 5, which means to call C-style-free() directly from the Flutter/dart side to release the memory of `jsonResponse`.

In fact, when I was handling the release logic for the green memory in the diagram, I was considering this method. For this example, it is workable. I have also found a `free()` wrapper that has already been implemented in the current polygonid-flutter-sdk code:

    ```dart
    late final _freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'free');
    late final _free =
      _freePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

    ffi.Pointer<ffi.Void> realloc(
        ffi.Pointer<ffi.Void> __ptr,
        int __size,
    ) {
        return _realloc(
        __ptr,
        __size,
        );
    }
    ```

The reason for adopting the method in Diagram A in current pull request, i.e. releasing `jsonResponse` through Go instead of flutter/dart, is mainly due to two considerations:

1. The release of `PLGNStatus` and the handling of C-Style String in Rust both follow the pattern in Diagram A, i.e. flutter does not directly call the c free function to release this part of the memory, but instead releases it through the lib that allocates this memory (golang/rust). Therefore, I have also adopted this design.

   ```go
   //export PLGNFreeStatus
   func PLGNFreeStatus(status *C.PLGNStatus) {
       _, cancel := logAPITime()
       defer cancel()

       if status == nil {
           return
       }

       if status.error_msg != nil {
           C.free(unsafe.Pointer(status.error_msg))
       }

       C.free(unsafe.Pointer(status))
   }
   ```

   <https://github.com/0xPolygonID/polygonid-flutter-sdk/blame/ad8b622c922c3ac9d86662e7cdf3c22823b592bd/rust/src/lib.rs#L583-L589>

   ```rust
   #[no_mangle]
   pub extern fn cstring_free(str: *mut c_char) {
       unsafe {
           if str.is_null() { return }
           CString::from_raw(str)
       };
   }
   ```

2. In my own understanding, although it seems that flutter can directly call c free in this case, but if we consider the following situations, the pattern in Diagram A may be more universal.

   - In case that we add a string variable to `PLGNStatus`, if we adopt the method in Diagram A, we only need to modify golang, and there is no need to change flutter, which can prevent memory leaks.

   ```go
   typedef struct _PLGNStatus
   {
           PLGNStatusCode status;
           char *error_msg;
           char *new_string; //added new string variable
   } PLGNStatus;

   func maybeCreateStatus(status **C.PLGNStatus, code C.PLGNStatusCode,
       msgFmt string, msgParams ...interface{}) {

       if status == nil {
           return
       }

       s := (*C.PLGNStatus)(C.malloc(C.sizeof_PLGNStatus))
       if s == nil {
           return
       }

       if msgFmt != "" {
           msg := fmt.Sprintf(msgFmt, msgParams...)
           s.error_msg = C.CString(msg)
       } else {
           s.error_msg = nil
       }

       s.status = code

       s.new_string = C.CString(xxxxxx) //new memory block allocated here

       *status = s
   }

       //export PLGNFreeStatus
       func PLGNFreeStatus(status *C.PLGNStatus) {
       _, cancel := logAPITime()
       defer cancel()

       if status == nil {
           return
       }

       if status.error_msg != nil {
           C.free(unsafe.Pointer(status.error_msg))
       }

       if status.new_string != nil {
           //free the newly added variable in Golang
           C.free(unsafe.Pointer(status.new_string))
       }

       C.free(unsafe.Pointer(status))
   }
   ```

   If we use the method in Diagram B, flutter also needs to add a free for new_string synchronously.

   In this way, we must maintain synchronous modifications in two different repositories. If there is no synchronous modification, it will cause memory leaks or other memory management problems.

   In particular, memory leaks, because they will not have an obvious impact on the running results during the development phase, so it is difficult to discover in a timely manner.

   - Regarding the `PLGNFreeCString()` function that will be added in this PR, there are also the following scenarios:

   `PLGNFreeCString()` does not only provide a C.free() function for Flutter, but it should be understood as "Flutter/Dart informs Golang through this function that the memory block Golang allocated will not be used anymore, and Golang can handle this memory block subsequently".

   Another situation is that memory allocation is not only done through C.CString()/malloc(), but can also be done through a method such as boost::pool, which pre-allocates a large block of memory and manages it through internal marking, without needing to call malloc()/free() provided by OS every time an allocate/release function is called.

   In such cases, Golang may replace the current C.CString()/C.free() calls by linking to a third-party library. If this situation arises, it is not appropriate for Flutter to continue calling C-style-free().

   If we adopt Diagram A's approach, which is the approach taken in this PR, where the responsibility for allocating and releasing memory is borne by Golang, and the method used is also determined by Golang.

   Then the Flutter code does not need to be modified, even if the native library changes this part of the memory management method. This approach is more in line with the RAII principle of "who allocates, who releases".

A summary in one sentence is: "Memory allocated by Flutter is released by Flutter, and memory allocated by Golang is released by Golang."

Actually, the above content is not limited to Flutter and Golang. Any cross-programming language memory management will encounter such situations.

Another issue is: for the module that allocates a block of memory, if this block of memory is released by other modules/languages, but the allocator module has not received a notification, this can also bring potential problems to memory management.

**Comment by yushihang** [comment]
Thank you for the discussion and insights~

> So whatever you do, you can't cause a memory leak inside Go runtime, only in system memory (I hope).

Yes, currently, the memory leak only occurs in the memory allocated by C.CString() (red memory in diagram), and not in the memory managed by Go's Garbage Collector.


> There are a lot of functions in standard library that return strings: like `asprintf` in `stdio.h` and they do not provide additional function to free those strings. Those allocated strings are supposed to be release with just calling the `free` function.

I agree with your point. 
However, the example you provided is within the same programming language or same module, sometimes this is the chosen implementation because there is no better alternative.

1. In our case,  it's malloc/free across different modules/libraries and even different programming languages, which leads to memory allocation and deallocation operations not being paired in each module. 

    A reader of this code might be confused as to why Golang only has C.CString() without C.free(), while Flutter has free() but lacks a corresponding malloc().

2. Let's take a look at the documentation for asprintf.
```
The functions asprintf() and vasprintf() are analogs of
       sprintf and vsprintf, except that they allocate a string
       large enough to hold the output including the terminating null
       byte ('\0'), and return a pointer to it via the first argument.
       This pointer should be passed to free() to release the allocated
       storage when it is no longer needed.
```
The Standard C library provide `asprintf()` and `free()`, so it require the caller using `free()` to release the memory allocated in `asprintf()`.

Correspondingly, C-polygonid provide `PLGNCreateClaim()` and `PLGNFreeCString()`, and  require the caller using `PLGNFreeCString()` to release to memory allocated in `PLGNCreateClaim()`. That sounds reasonable as well.


3. Indeed, in cases where we have already constrained Golang to exclusively use C.CString() for memory allocation from the operating system, there won't be any technical issues with calling the corresponding C.free() in Flutter(). It is the same for both string and PLGNStatus.  (Assuming that we ensure the allocation and deallocation operations are paired on both ends)

    What we're discussing here is more of a design choice~


4. Additionally, if simple strings can be directly freed by Flutter, but PLGNStatus requires PLGNFreeStatus(), this may lead to inconsistent code styles. 
    However, if we individually free the strings in PLGNStatus in Flutter, it becomes overly coupled. 
    Furthermore, babyjubjub(rust) already provides a cstring_free() function<https://github.com/0xPolygonID/polygonid-flutter-sdk/blame/ad8b622c922c3ac9d86662e7cdf3c22823b592bd/rust/src/lib.rs#L584>. 

   This means that in the Flutter side of the code, there will be some direct calls to C.free (without corresponding malloc), while in others similar codes , PLGNFreeStatus()/cstring_free() is used, which may seem a bit odd?

**Comment by yushihang** [comment]
>You talk about some "exotic" types like C.CString

There might be a misunderstanding here. 
I was not talking about C.CString() type, but rather the Golang functions used to allocate memory for C-type variables in the c-polygonid library, such as the following calls:

https://github.com/0xPolygonID/c-polygonid/blob/cc0573dddca20fb0b587b4e415f1b7f9c7a32132/cmd/polygonid/polygonid.go#L422


> > [User] What is CString stands for in `PLGNFreeCString`?
> > [Me] That is a function name that created a `char*` string inside a `c-polygonid` library
> > [User] Why should I use `PLGNFreeCString` instead of `free`
> > [Me] You shouldn't, they are the same.
> > [User] Then why `PLGNFreeCString` exists?
> > [Me] Em...

This conversation is a good point to discuss~

Suppose we add comments to PLGNCreateClaim() like asprintf() 
```
The jsonResponse pointer should be passed to PLGNFreeCString() to release the allocated
       storage when it is no longer needed.
```

As a programmer calling PLGNCreateClaim(), I would certainly be curious and look into the implementation of PLGNFreeCString(), but I would not choose to directly call free by my side.

Because the caller don't need to maintain the implementation of PLGNFreeCString() and PLGNCreateClaim(),  the c-polygonid library will ensure consistent memory management.  As long as PLGNFreeCString() and PLGNCreateClaim() are called in pairs according to  the document.


>As to confusion, from my point of view, it can be confusing why I can't release pointer to char just by calling free

I got your point~ 

It is not an issue of "right or wrong", but of "right or better". It's true we can call `free()' to free the memory in flutter,  but a `allocate/release' pair in a same module will be better to understand.

**Pull request closed without merging**
