### PR TITLE
Migrate to Dart 3

### PR DESCRIPTION
**Pull request by AyushBherwani1998**
This is an attempt to migrate the plugin to Dart 3 and improve the performance. Dart 3 introduces sound null safety, and hence have updated the analysis_options to use the language features and improve the performance. That being said, Dart 3 also introduces [other good features](https://medium.com/dartlang/announcing-dart-3-53f065a10635) like records, pattern matching, and also native interop. Would be happy to contribute, and add use those features.

### CODE REVIEW

**Comment by Plumillon** [comment]
Thanks a lot for your contribution, awesome thinking about updating to Dart 3!

**Review by Plumillon — CHANGES_REQUESTED** [review]
Can you please:

- [ ] update `example/pubspec.yaml`:
```
dependencies:
  envied: ^0.3.0+3

dev_depencies:
  envied_generator: ^0.3.0+3
```
- [ ] Then `example/lib/src/common/env.dart`:
`static const String polygonMumbai = _Env.polygonMumbai;`

**Comment by Plumillon** [comment]
Merged to `develop` from [here](https://github.com/0xPolygonID/polygonid-flutter-sdk/pull/311).
Thx a lot @AyushBherwani1998

**Comment by AyushBherwani1998** [comment]
Happy to contribute @Plumillon. I'll send few more PRs to cleanup and use Dart 3 features.

**Pull request merged**
